version: '3.8'

services:
  db-test:
    image: postgres:15.1-alpine
    volumes:
      - pgdata-test/:/var/lib/postgresql/data/
    ports:
      - 5434:5432
    env_file:
      - .docker-test.env
    networks:
      - nettest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${DB_NAME} -U $${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 3

  cache-test:
    image: redis:6.2-alpine
    ports:
      - 6381:6379
    env_file:
      - .docker-test.env
    command: redis-server /etc/redis/6379.conf
    networks:
      - netcachetest
    volumes:
      - cache-test:/data

  api-test:
    build:
      context: ./src
      dockerfile: Dockerfile-test
    command: |
      bash -c 'pytest -v'
    volumes:
      - app-test:/src
    ports:
      - 8080:8000
    env_file:
      - .docker-test.env
    networks:
      - nettest
      - netcachetest
    depends_on:
      db-test:
        condition: service_healthy

volumes:
  pgdata-test:
  cache-test:
  app-test:

networks:
  nettest: {}
  netcachetest:
    driver: bridge
